apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service-8081
  labels:
    test: test
    labele2: label
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    run: spring-boot-sample-8081
  sessionAffinity: None
  type: ClusterIP

